baseURL = "https://volkamerlab.org/"
languageCode = "en-us"
title = "Volkamer Lab"
author = "Volkamer Lab"
[pagination]
  pagerSize = 5

[permalinks]
  blog = "/:year/:month/:filename/"

# This is needed to allow HTML in our markdown files
[markup.goldmark.renderer]
unsafe = true
